AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  uprevit-backend

  Sample SAM Template for uprevit-backend

Parameters:
  MONGODB_URI:
    Type: String
    Description: "MongoDB connection string URI"
    Default: "mongodb://host.docker.internal:27017"
  DB_NAME:
    Type: String
    Description: "MongoDB database name"
    Default: "uprevit"

# ──────────────────────────────────────────────────────────────────────────
# TOP-LEVEL METADATA  – YAML anchor for the build recipe
# ──────────────────────────────────────────────────────────────────────────
Metadata:
  # Common part that never changes
  EsbuildBase: &EsbuildBase
    BuildMethod: esbuild

  # Common BuildProperties (minus EntryPoints)
  EsbuildProps: &EsbuildProps
    Minify: true
    Target: es2020
    Sourcemap: true

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Tracing: Active
    Environment:
      Variables:
        MONGODB_URI: !Ref MONGODB_URI
        DB_NAME: !Ref DB_NAME
        USER_POOL_ID: !Ref USER_POOL_ID
        CLIENT_ID: !Ref CLIENT_ID
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON

  Api:
    TracingEnabled: true
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [app.ts]

  # ──────────────────────────────────────────────────────────────────────────
  # USERS
  # ──────────────────────────────────────────────────────────────────────────
  CreateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/users/createUser.lambdaHandler
      Events:
        CreateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: post
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/users/createUser.ts]

  GetUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/users/getUser.lambdaHandler
      Events:
        GetUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{id}
            Method: get
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/users/getUser.ts]

  UpdateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/users/updateUser.lambdaHandler
      Events:
        UpdateUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users
            Method: put
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/users/updateUser.ts]

  DeleteUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/users/deleteUser.lambdaHandler
      Events:
        DeleteUser:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{id}
            Method: delete
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/users/deleteUser.ts]

  # ──────────────────────────────────────────────────────────────────────────
  # WORKSPACES
  # ──────────────────────────────────────────────────────────────────────────
  CreateWorkspaceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/workspaces/createWorkspace.lambdaHandler
      Events:
        CreateWorkspace:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /workspace
            Method: post
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/workspaces/createWorkspace.ts]

  GetWorkspaceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/workspaces/getWorkspace.lambdaHandler
      Events:
        GetWorkspace:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /workspace/{id}
            Method: get
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/workspaces/getWorkspace.ts]

  UpdateWorkspaceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/workspaces/updateWorkspace.lambdaHandler
      Events:
        UpdateWorkspace:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /workspace
            Method: put
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/workspaces/updateWorkspace.ts]

  # ──────────────────────────────────────────────────────────────────────────
  # DEPARTMENTS
  # ──────────────────────────────────────────────────────────────────────────
  CreateDepartmentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/departments/createDepartment.lambdaHandler
      Events:
        CreateDepartment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /departments
            Method: post
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/departments/createDepartment.ts]

  GetDepartmentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/departments/getDepartment.lambdaHandler
      Events:
        GetDepartment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /departments/{id}
            Method: get
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/departments/getDepartment.ts]

  GetAllDepartmentsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-0-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/departments/getAllDepartments.lambdaHandler
      Events:
        GetAllDepartments:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-0-31.md#api
          Properties:
            Path: /departments
            Method: get
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/departments/getAllDepartments.ts]

  UpdateDepartmentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/departments/updateDepartment.lambdaHandler
      Events:
        UpdateDepartment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /departments
            Method: put
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/departments/updateDepartment.ts]

  ArchiveDepartmentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/departments/archiveDepartment.lambdaHandler
      Events:
        ArchiveDepartment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /departments/{id}
            Method: patch
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/departments/archiveDepartment.ts]

  # ──────────────────────────────────────────────────────────────────────────
  # PROJECTS
  # ──────────────────────────────────────────────────────────────────────────

  CreateProjectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/projects/createProject.lambdaHandler
      Events:
        CreateProject:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /projects
            Method: post
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/projects/createProject.ts]

  UpdateProjectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/projects/updateProject.lambdaHandler
      Events:
        UpdateProject:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /projects
            Method: put
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/projects/updateProject.ts]

  GetAllProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/projects/getAllProjects.lambdaHandler
      Events:
        GetAllProjects:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /projects
            Method: get
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/projects/getAllProjects.ts]

  ArchiveProjectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/projects/archiveProject.lambdaHandler
      Events:
        ArchiveProject:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /projects/{id}
            Method: patch
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/projects/archiveProject.ts]

  # ──────────────────────────────────────────────────────────────────────────
  # PRODUCTS
  # ──────────────────────────────────────────────────────────────────────────

  CreateProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: controllers/products/createProduct.lambdaHandler
      Events:
        CreateProduct:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /products
            Method: post
    Metadata:
      <<: *EsbuildBase
      BuildProperties:
        <<: *EsbuildProps
        EntryPoints: [controllers/products/createProduct.ts]

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: "true"
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
